name: virustotal

on:
  workflow_call:

jobs:
  vt-scan:
    name: Scan EFI with VirusTotal
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compress EFI to EFI.zip
        run: zip -r -X EFI.zip EFI

      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v3
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            ./EFI.zip
          request_rate: 4
          update_release_body: true
